export const tripConfig = {
  reference: "LV-2026-CHN-047",
  client: {
    name: "Famille Martin",
    travelers: 4,
    details: "2 adultes · 2 enfants (8 et 12 ans)",
  },
  destination: "Chine",
  flag: "🇨🇳",
  heroImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=1600&q=80&auto=format&fit=crop",
  mapZoom: 5,
  departDate: "2026-09-15T06:00:00",
  returnDate: "2026-10-05T20:00:00",
  duration: 21,
  currency: {
    code: "CNY",
    symbol: "¥",
    name: "Yuan chinois",
    rate: 7.8,
    presets: [50, 100, 200, 500, 1000],
  },
  budget: {
    total: 8000,
    categories: [
      { id: "vols", label: "Vols A/R", amount: 2800, icon: "✈️", color: "blue" },
      { id: "hebergement", label: "Hébergements", amount: 2100, icon: "🏨", color: "purple" },
      { id: "transport", label: "Transports locaux", amount: 600, icon: "🚄", color: "emerald" },
      { id: "repas", label: "Repas & restaurants", amount: 1050, icon: "🍜", color: "orange" },
      { id: "activites", label: "Activités & visites", amount: 750, icon: "🎭", color: "pink" },
      { id: "shopping", label: "Shopping & souvenirs", amount: 500, icon: "🛍️", color: "yellow" },
      { id: "assurance", label: "Assurance voyage", amount: 200, icon: "🛡️", color: "slate" },
    ],
  },
  regions: [
    {
      id: "beijing",
      name: "Pékin",
      emoji: "🏯",
      dates: "15–19 sept.",
      nights: 4,
      hotel: "Grand Millennium Beijing",
      color: "red",
      description: "La capitale impériale",
      coords: [39.9163, 116.3972],
      image: "https://images.unsplash.com/photo-1603120527222-33f28c2ce89e?w=1200&q=80&auto=format&fit=crop",
    },
    {
      id: "xian",
      name: "Xi'an",
      emoji: "⚔️",
      dates: "20–23 sept.",
      nights: 3,
      hotel: "Sofitel Legend Peoples Grand Hotel",
      color: "amber",
      description: "Berceau de la civilisation chinoise",
      coords: [34.3416, 108.9398],
      image: "https://images.unsplash.com/photo-1527922891260-918d42a4efc8?w=1200&q=80&auto=format&fit=crop",
    },
    {
      id: "chengdu",
      name: "Chengdu",
      emoji: "🐼",
      dates: "24–27 sept.",
      nights: 3,
      hotel: "Niccolo Chengdu",
      color: "emerald",
      description: "La ville des pandas et de la gastronomie",
      coords: [30.5728, 104.0668],
      image: "https://images.unsplash.com/photo-1540126034813-121bf29033d2?w=1200&q=80&auto=format&fit=crop",
    },
    {
      id: "shanghai",
      name: "Shanghai",
      emoji: "🌆",
      dates: "28 sept. – 5 oct.",
      nights: 7,
      hotel: "The Bund Hotel by Marriott",
      color: "blue",
      description: "La métropole du futur",
      coords: [31.2397, 121.4994],
      image: "https://images.unsplash.com/photo-1545893835-abaa50cbe628?w=1200&q=80&auto=format&fit=crop",
    },
  ],
  itinerary: [
    {
      regionId: "beijing", day: 1, date: "2026-09-15", dayLabel: "Mardi 15 septembre",
      title: "Arrivée à Pékin", highlight: "✈️ Vol Air France AF128 — Paris CDG 08h10",
      planB: "En cas de retard : dîner au restaurant de l'hôtel, cuisine cantonaise.",
      hackSimple: "💡 Téléchargez DiDi (l'Uber chinois) dès l'aéroport — plus simple et moins cher que le taxi.",
      steps: [
        { time: "08h10", icon: "✈️", title: "Décollage Paris CDG", desc: "Vol AF128 direct Pékin Capital (PEK) · 10h05 de vol", outdoor: false },
        { time: "22h15", icon: "🛬", title: "Arrivée Pékin Capital", desc: "Douane, bagages, transfert privé hôtel", outdoor: false },
        { time: "23h30", icon: "🏨", title: "Check-in Grand Millennium Beijing", desc: "Quartier CBD, vue panoramique sur Pékin.", outdoor: false },
      ],
    },
    {
      regionId: "beijing", day: 2, date: "2026-09-16", dayLabel: "Mercredi 16 septembre",
      title: "Le cœur impérial", highlight: "🏯 Cité Interdite + Place Tiananmen",
      planB: "Foule excessive : Palais d'Été en alternative (moins touristique).",
      hackSimple: "💡 Réservez vos billets Cité Interdite la veille (quota : 40 000 visiteurs/jour).",
      steps: [
        { time: "08h00", icon: "🍳", title: "Petit-déjeuner à l'hôtel", desc: "Buffet international + dim sum", outdoor: false },
        { time: "09h00", icon: "🏛️", title: "Place Tiananmen", desc: "La plus grande place du monde, portrait Mao, cérémonie des couleurs", outdoor: true },
        { time: "10h00", icon: "🏯", title: "Cité Interdite (Gugong)", desc: "720 bâtiments, 9 999 pièces. Audioguide famille disponible.", outdoor: true },
        { time: "13h30", icon: "🍜", title: "Canard laqué de Pékin — Bianyifang", desc: "Fondé en 1416 — LA référence historique du canard laqué", outdoor: false },
        { time: "15h00", icon: "🌿", title: "Parc Jingshan", desc: "Vue panoramique sur la Cité Interdite depuis la colline du Charbon", outdoor: true },
        { time: "16h30", icon: "🛕", title: "Beihai Park", desc: "Lac et pagode blanche, balade en barque (enfants adorent !)", outdoor: true },
        { time: "19h00", icon: "🍽️", title: "Dîner dans les Hutongs", desc: "Nanluoguxiang — ruelles historiques, street food authentique", outdoor: true },
      ],
    },
    {
      regionId: "beijing", day: 3, date: "2026-09-17", dayLabel: "Jeudi 17 septembre",
      title: "La Grande Muraille", highlight: "🧱 Section Mutianyu — La plus spectaculaire",
      planB: "Météo nuageuse ? La muraille dans le brouillard est encore plus mystérieuse.",
      hackSimple: "💡 Téléphérique à la montée, luge à la descente — les enfants vont adorer !",
      steps: [
        { time: "07h30", icon: "🚌", title: "Départ pour Mutianyu", desc: "Minibus privé depuis l'hôtel (1h30 de route)", outdoor: false },
        { time: "09h30", icon: "🧱", title: "Grande Muraille — Section Mutianyu", desc: "Mieux restaurée qu'à Badaling, moins de touristes. Téléphérique + 2h de marche.", outdoor: true },
        { time: "12h30", icon: "🍱", title: "Pique-nique panoramique", desc: "Repas avec vue sur la muraille à perte de vue", outdoor: true },
        { time: "14h00", icon: "🎿", title: "Descente en luge !", desc: "Toboggan depuis la muraille — expérience inoubliable pour les enfants", outdoor: true },
        { time: "16h30", icon: "🚌", title: "Retour à Pékin", desc: "Arrêt optionnel au village de l'époque Ming", outdoor: false },
        { time: "19h30", icon: "🍲", title: "Hot-Pot Haidilao", desc: "Service légendaire, bouillons variés — bouillon doux pour les enfants", outdoor: false },
      ],
    },
    {
      regionId: "beijing", day: 4, date: "2026-09-18", dayLabel: "Vendredi 18 septembre",
      title: "Temples & Opéra de Pékin", highlight: "🛕 Temple du Ciel + Opéra impérial",
      planB: "Musée National de Chine si pluie (gratuit, collection exceptionnelle).",
      hackSimple: "💡 Arrivez au Temple du Ciel à 6h — les Pékinois font leurs exercices matinaux, scène unique.",
      steps: [
        { time: "07h00", icon: "🛕", title: "Temple du Ciel — Tian Tan", desc: "Lever du soleil, exercices matinaux des locaux, jardins impériaux", outdoor: true },
        { time: "10h00", icon: "🎨", title: "Quartier artistique 798", desc: "Usines Bauhaus réhabilitées en galeries — parfait pour les enfants créatifs", outdoor: false },
        { time: "13h00", icon: "🥟", title: "Déjeuner raviolis pékinois", desc: "Bijiapei Dumplings — raviolis faits main, cours de confection possible", outdoor: false },
        { time: "15h00", icon: "🛍️", title: "Marché Panjiayuan", desc: "Le plus grand marché aux antiquités d'Asie", outdoor: true },
        { time: "19h30", icon: "🎭", title: "Opéra de Pékin (Jingju)", desc: "Théâtre Chang'an — costumes et maquillages extraordinaires", outdoor: false },
      ],
    },
    {
      regionId: "beijing", day: 5, date: "2026-09-19", dayLabel: "Samedi 19 septembre",
      title: "Palais d'Été & Train vers Xi'an", highlight: "🌸 Le Versailles chinois + TGV",
      planB: "Musée National si déjà visité le Palais.",
      hackSimple: "💡 Train 1ère classe pour Xi'an : 20€ de plus pour un confort bien supérieur avec enfants.",
      steps: [
        { time: "08h00", icon: "🏛️", title: "Palais d'Été — 颐和园", desc: "Lac Kunming, Temple de la Longévité, bateau dragon avec les enfants", outdoor: true },
        { time: "12h00", icon: "🍜", title: "Déjeuner au pavillon du lac", desc: "Restaurant traditionnel dans l'enceinte du palais", outdoor: false },
        { time: "14h00", icon: "🧳", title: "Retour hôtel, check-out", desc: "Dépôt bagages, dernier tour Wangfujing Street", outdoor: false },
        { time: "17h30", icon: "🚄", title: "TGV Pékin Ouest → Xi'an Nord", desc: "G87 · Départ 18h02 · Arrivée 22h31 · 4h29 · 1ère classe", outdoor: false },
        { time: "22h45", icon: "🏨", title: "Check-in Xi'an — Sofitel Legend", desc: "Au cœur de la vieille ville fortifiée", outdoor: false },
      ],
    },
    {
      regionId: "xian", day: 6, date: "2026-09-20", dayLabel: "Dimanche 20 septembre",
      title: "Découverte de Xi'an", highlight: "🧱 Remparts + Quartier Musulman",
      planB: "Pluie : Musée de Xi'an (collections dynastiques, gratuit).",
      hackSimple: "💡 Louez des vélos sur les remparts — faire les 13,7km du tour est une expérience unique !",
      steps: [
        { time: "09h00", icon: "🧱", title: "Remparts de Xi'an à vélo", desc: "Tour complet des remparts (13,7km), vue sur la vieille ville", outdoor: true },
        { time: "12h00", icon: "🕌", title: "Grande Mosquée de Xi'an", desc: "Architecture sino-islamique unique, fondée en 742 ap. J.-C.", outdoor: true },
        { time: "13h00", icon: "🥙", title: "Quartier Musulman (Huimin Jie)", desc: "Brochettes d'agneau, Rou Jia Mo (burger chinois), jus de grenade frais", outdoor: false },
        { time: "16h00", icon: "🎆", title: "Spectacle fontaines musicales", desc: "Place de la Tour de la Cloche — son et lumière quotidien gratuit", outdoor: true },
        { time: "19h30", icon: "🍝", title: "Biang Biang Noodles", desc: "Les nouilles plates XL emblématiques de Xi'an — expérience incontournable", outdoor: false },
      ],
    },
    {
      regionId: "xian", day: 7, date: "2026-09-21", dayLabel: "Lundi 21 septembre",
      title: "L'Armée de Terre Cuite", highlight: "⚔️ Les 8 000 guerriers de l'Empereur Qin",
      planB: "La fosse N°1 est couverte — idéal même sous la pluie.",
      hackSimple: "💡 Guide local indispensable — les enfants adorent l'histoire de la découverte accidentelle en 1974.",
      steps: [
        { time: "08h00", icon: "🚌", title: "Départ pour le Mausolée de l'Empereur Qin", desc: "35km à l'est, 45 min en bus privé", outdoor: false },
        { time: "09h00", icon: "⚔️", title: "Armée de Terre Cuite — Fosse N°1", desc: "6 000 guerriers grandeur nature. Audioguide famille inclus.", outdoor: false },
        { time: "11h00", icon: "🗿", title: "Fosses N°2 et N°3", desc: "Cavalerie, officiers — ateliers de restauration visibles en direct", outdoor: false },
        { time: "13h00", icon: "🍱", title: "Déjeuner sur site", desc: "Restaurant historique dans l'enceinte du mausolée", outdoor: false },
        { time: "14h00", icon: "👑", title: "Tumulus de l'Empereur Qin Shi Huang", desc: "La pyramide non-excavée de l'Unificateur de la Chine (210 av. J.-C.)", outdoor: true },
        { time: "19h00", icon: "🍲", title: "Hot-pot style Nord-Ouest", desc: "Moins épicé qu'à Chengdu — parfait pour les enfants", outdoor: false },
      ],
    },
    {
      regionId: "xian", day: 8, date: "2026-09-22", dayLabel: "Mardi 22 septembre",
      title: "Culture & Pagodes", highlight: "🏯 Pagode de la Grande Oie Sauvage",
      planB: "Forêt de stèles (Beilin Museum) — calligraphie chinoise.",
      hackSimple: "💡 Son et lumière nocturne autour de la Pagode — magnifique pour les photos de famille.",
      steps: [
        { time: "09h00", icon: "🏯", title: "Pagode de la Grande Oie Sauvage", desc: "Bouddhisme Tang (652 ap. J.-C.), temple actif, vue panoramique", outdoor: true },
        { time: "11h00", icon: "🎨", title: "Atelier calligraphie pour enfants", desc: "1h dans un atelier traditionnel — souvenir fait-main unique !", outdoor: false },
        { time: "13h00", icon: "🥢", title: "Banquet de la Dynastie Tang", desc: "Reconstitution des fastes impériaux — présentation spectaculaire", outdoor: false },
        { time: "15h00", icon: "🏛️", title: "Musée du Shaanxi", desc: "1,4 million d'objets — les enfants adorent l'armée miniature en or", outdoor: false },
        { time: "20h00", icon: "🎭", title: "Spectacle Danses Tang", desc: "Théâtre Shaanxi Grand — fêtes impériales reconstituées", outdoor: false },
      ],
    },
    {
      regionId: "xian", day: 9, date: "2026-09-23", dayLabel: "Mercredi 23 septembre",
      title: "Dernier matin & TGV Chengdu", highlight: "🐼 Direction la capitale des Pandas !",
      planB: "Arrivée tardive : dîner hot-pot à l'hôtel de Chengdu.",
      hackSimple: "💡 Achetez des dattes rouges et noix séchées à la gare — spécialités de Xi'an.",
      steps: [
        { time: "08h00", icon: "🛕", title: "Temple de la Petite Oie Sauvage", desc: "Plus intime, moines actifs — bouddhisme vivant", outdoor: true },
        { time: "10h00", icon: "🧳", title: "Check-out & shopping", desc: "Dernier tour du Quartier Musulman, achats épices locales", outdoor: false },
        { time: "13h00", icon: "🍜", title: "Dernier Biang Biang Noodles", desc: "Vous allez regretter de ne plus pouvoir en manger !", outdoor: false },
        { time: "15h30", icon: "🚄", title: "TGV Xi'an Nord → Chengdu Est", desc: "Départ 16h12 · Arrivée 19h37 · 3h25 · 1ère classe", outdoor: false },
        { time: "20h00", icon: "🏨", title: "Check-in Chengdu — Niccolo", desc: "Taikoo Li — le quartier le plus branché de Chengdu", outdoor: false },
      ],
    },
    {
      regionId: "chengdu", day: 10, date: "2026-09-24", dayLabel: "Jeudi 24 septembre",
      title: "Les Pandas Géants !", highlight: "🐼 Base de Recherche des Pandas de Chengdu",
      planB: "Pandas dormants l'après-midi : Zoo de Chengdu (tigres blancs, girafes).",
      hackSimple: "💡 Arrivez à 8h — les pandas sont actifs le matin pour le repas de bambou.",
      steps: [
        { time: "07h30", icon: "🚌", title: "Départ pour la Base Pandas", desc: "30 min depuis l'hôtel — arrivée avant la foule", outdoor: false },
        { time: "08h00", icon: "🐼", title: "Pandas Géants — Repas du matin", desc: "Les voir manger le bambou, programme gardiennage optionnel (+150€ famille)", outdoor: true },
        { time: "11h00", icon: "🦊", title: "Pandas Roux", desc: "Adorables et actifs le matin — les enfants vont craquer !", outdoor: true },
        { time: "13h00", icon: "🍜", title: "Déjeuner Mapo Tofu", desc: "Plat emblématique — demandez 'micro là' (peu épicé) pour les enfants", outdoor: false },
        { time: "15h00", icon: "🛕", title: "Temple de Wenshu", desc: "Monastère bouddhiste actif, jardin de thé traditionnel", outdoor: true },
        { time: "19h30", icon: "🌶️", title: "Hot-Pot Sichuanais — Haidilao", desc: "Le vrai hot-pot épicé de Chengdu ! Bouillon doux pour les enfants.", outdoor: false },
      ],
    },
    {
      regionId: "chengdu", day: 11, date: "2026-09-25", dayLabel: "Vendredi 25 septembre",
      title: "Buddha Géant de Leshan", highlight: "🗿 Le plus grand Bouddha du monde",
      planB: "Pluie : Musée Sanxingdui (civilisation mystérieuse 3 000 ans av. J.-C.).",
      hackSimple: "💡 Prenez le bateau — depuis la berge on ne voit que la tête, depuis l'eau on voit les 71m entiers !",
      steps: [
        { time: "07h00", icon: "🚌", title: "Départ pour Leshan", desc: "2h de route depuis Chengdu (130km)", outdoor: false },
        { time: "09h30", icon: "🚤", title: "Bateau sur la rivière Min", desc: "Vue complète sur le Grand Bouddha (71m) depuis l'eau", outdoor: true },
        { time: "11h00", icon: "🗿", title: "Descente vers les pieds du Bouddha", desc: "Escalier taillé dans la falaise — vue sur les orteils géants", outdoor: true },
        { time: "13h00", icon: "🍱", title: "Déjeuner poissons de rivière", desc: "Spécialité de Leshan — grillés, marinés aux épices locales", outdoor: false },
        { time: "18h00", icon: "🚌", title: "Retour Chengdu", desc: "2h de route", outdoor: false },
        { time: "20h00", icon: "🎭", title: "Opéra sichuanais + Changement de masque", desc: "Face-changing (Bian Lian) — magie pure, les enfants sont bouche bée !", outdoor: false },
      ],
    },
    {
      regionId: "chengdu", day: 12, date: "2026-09-26", dayLabel: "Samedi 26 septembre",
      title: "Cuisine & Rues de Chengdu", highlight: "🌶️ Cours de cuisine sichuanaise en famille",
      planB: "Jardin de bambou géant de Dujiangyan si météo parfaite.",
      hackSimple: "💡 Le poivre de Sichuan crée une sensation d'engourdissement unique — sans brûler. Les enfants adorent l'expérience !",
      steps: [
        { time: "09h00", icon: "👨‍🍳", title: "Cours de cuisine sichuanaise", desc: "Famille Martin aux fourneaux — Mapo Tofu, Kung Pao, Dumplings. Recettes remises !", outdoor: false },
        { time: "12h00", icon: "🍽️", title: "Déjeuner : vous avez cuisiné !", desc: "Dégustation de vos créations avec le chef", outdoor: false },
        { time: "14h00", icon: "🏘️", title: "Quartier de Jinli", desc: "Rues de la Dynastie Han, boutiques artisanat, lanternes rouges, street food", outdoor: true },
        { time: "16h00", icon: "🎨", title: "Atelier masques de l'Opéra", desc: "Peignez votre propre masque — souvenir unique fait-main !", outdoor: false },
        { time: "19h00", icon: "🍢", title: "Marché de nuit Kuanzhai Alley", desc: "Les ruelles larges et étroites — atmosphère magique en soirée", outdoor: true },
      ],
    },
    {
      regionId: "chengdu", day: 13, date: "2026-09-27", dayLabel: "Dimanche 27 septembre",
      title: "Dernières saveurs & Vol Shanghai", highlight: "✈️ Chengdu → Shanghai en soirée",
      planB: "Décalage vol : restaurant sichuanais à l'aéroport Tianfu.",
      hackSimple: "💡 Aéroport Tianfu : le plus récent de Chine, impressionnant — arrivez 2h30 avant.",
      steps: [
        { time: "08h30", icon: "🌿", title: "Jardin de thé Renmin Park", desc: "Rituel matinal chengdunais — thé au jasmin, jeux de cartes, coiffeurs en plein air", outdoor: true },
        { time: "12h30", icon: "🍜", title: "Dernier déjeuner sichuanais", desc: "Dan Dan Noodles et boulettes de riz au sésame — les enfants en redemandent", outdoor: false },
        { time: "14h00", icon: "🧳", title: "Check-out & transfer aéroport", desc: "1h30 jusqu'à l'aéroport Tianfu", outdoor: false },
        { time: "17h20", icon: "✈️", title: "Vol Chengdu → Shanghai Pudong", desc: "CA4505 · Décollage 18h35 · Arrivée 21h10 · 2h35", outdoor: false },
        { time: "22h00", icon: "🏨", title: "Check-in The Bund Hotel Shanghai", desc: "Vue imprenable sur le Bund — bienvenue à Shanghai !", outdoor: false },
      ],
    },
    {
      regionId: "shanghai", day: 14, date: "2026-09-28", dayLabel: "Lundi 28 septembre",
      title: "Le Bund & Pudong", highlight: "🌆 Le skyline le plus impressionnant du monde",
      planB: "Pluie : Aquarium de Shanghai ou Musée des Sciences et Technologie.",
      hackSimple: "💡 Croisière sur la Huangpu à 18h — voir le Bund s'illuminer depuis l'eau : photo de famille iconique.",
      steps: [
        { time: "09h00", icon: "🌉", title: "Le Bund — Waitan", desc: "Promenade face aux gratte-ciel de Pudong, architecture coloniale des années 30", outdoor: true },
        { time: "11h00", icon: "🏙️", title: "Tour Shanghai — 632m", desc: "Observation deck 118ème étage, vue 360° sur Shanghai", outdoor: false },
        { time: "13h00", icon: "🍱", title: "Déjeuner Dim Sum — Restaurant Michelin", desc: "Xiaolongbao (raviolis soupe) emblématiques — tour IFC", outdoor: false },
        { time: "15h00", icon: "🔭", title: "Planétarium de Shanghai", desc: "Le plus grand au monde (ouverture 2021) — les enfants adorent !", outdoor: false },
        { time: "18h00", icon: "🚤", title: "Croisière coucher de soleil Huangpu", desc: "Bund + Pudong illuminés — LA photo de famille du voyage", outdoor: true },
        { time: "20h30", icon: "🍽️", title: "Dîner Mr & Mrs Bund", desc: "Paul Pairet — fusion française/chinoise premium, vue directe sur le Bund", outdoor: false },
      ],
    },
    {
      regionId: "shanghai", day: 15, date: "2026-09-29", dayLabel: "Mardi 29 septembre",
      title: "Jardin Yu & Vieille Ville", highlight: "🏡 Jardin Yu — 5 siècles d'histoire",
      planB: "Trop fréquenté : Jardin Guilin en périphérie, beaucoup plus calme.",
      hackSimple: "💡 Arrivez à 8h — le jardin est vide et magnifique avant l'arrivée des groupes à 9h30.",
      steps: [
        { time: "08h00", icon: "🌺", title: "Jardin Yu (Yuyuan)", desc: "Chef-d'œuvre Ming, pavillons, rocailles, lotus — silence matinal", outdoor: true },
        { time: "10h00", icon: "🥟", title: "Xiaolongbao de Nanxiang", desc: "La boulangerie historique depuis 1900 — file d'attente mais incontournable !", outdoor: false },
        { time: "11h00", icon: "🛕", title: "Temple de la Ville-Dieu", desc: "Temple taoïste animé — vie religieuse locale authentique", outdoor: true },
        { time: "15h00", icon: "🏘️", title: "Xintiandi", desc: "Anciennes lilong réhabilitées en quartier branché — cafés, galeries", outdoor: true },
        { time: "17h30", icon: "🎨", title: "Tianzifang", desc: "Ruelles d'artistes dans les shikumen — artisanat, cafés bohèmes", outdoor: true },
        { time: "20h00", icon: "🍷", title: "Dîner Xintiandi", desc: "Crystal Jade ou Hakkasan — dim sum premium dans le quartier historique", outdoor: false },
      ],
    },
    {
      regionId: "shanghai", day: 16, date: "2026-09-30", dayLabel: "Mercredi 30 septembre",
      title: "Zhujiajiao — Village sur l'Eau", highlight: "🛶 La 'Venise de Shanghai'",
      planB: "Pluie : Musée de Shanghai (5 000 ans d'histoire, gratuit).",
      hackSimple: "💡 Partez à 8h — le village est vide et magnifique avant 10h. Après, la foule arrive.",
      steps: [
        { time: "08h00", icon: "🚌", title: "Départ pour Zhujiajiao", desc: "1h en métro + navette depuis le centre", outdoor: false },
        { time: "09h00", icon: "🛶", title: "Village sur l'eau de Zhujiajiao", desc: "Canaux, ponts en pierre, maisons Ming. Gondole avec batelier local.", outdoor: true },
        { time: "11h00", icon: "🦆", title: "Marché flottant", desc: "Les habitants font leurs courses sur les bateaux — photographies authentiques", outdoor: true },
        { time: "13h00", icon: "🍢", title: "Spécialités locales", desc: "Porc braisé, tofu fermenté, gâteaux de riz", outdoor: false },
        { time: "19h00", icon: "🍽️", title: "Dîner Nanjing Road", desc: "Pedestrian mall animé, dizaines de restaurants au choix", outdoor: true },
      ],
    },
    {
      regionId: "shanghai", day: 17, date: "2026-10-01", dayLabel: "Jeudi 1er octobre",
      title: "Fête Nationale Chinoise !", highlight: "🎆 1er octobre — Jour de la République",
      planB: "Très fréquenté aujourd'hui — profitez des festivités locales plutôt que des musées.",
      hackSimple: "💡 Feux d'artifice sur le Bund à 21h — les plus beaux de votre vie, garantis !",
      steps: [
        { time: "09h00", icon: "🎊", title: "Célébrations nationales", desc: "Décorations rouges partout, parades, musique traditionnelle dans les rues", outdoor: true },
        { time: "10h00", icon: "🌿", title: "Jardin Botanique de Shanghai", desc: "Moins touristique le 1er oct, magnifique en début d'automne", outdoor: true },
        { time: "15h00", icon: "🎡", title: "Parc d'attractions Jinjiang", desc: "Parc familial vintage de Shanghai — parfait aujourd'hui", outdoor: true },
        { time: "21h00", icon: "🎆", title: "Feux d'Artifice sur le Bund", desc: "Spectacle pyrotechnique national — le clou de la Fête Nationale", outdoor: true },
      ],
    },
    {
      regionId: "shanghai", day: 18, date: "2026-10-02", dayLabel: "Vendredi 2 octobre",
      title: "Musée de Shanghai", highlight: "🏛️ 5 000 ans de civilisation chinoise",
      planB: "Bibliothèque Nationale — architecture contemporaine époustouflante.",
      hackSimple: "💡 Le Musée de Shanghai est gratuit mais requiert une réservation en ligne 24h à l'avance.",
      steps: [
        { time: "09h00", icon: "🏛️", title: "Musée de Shanghai", desc: "Bronzes anciens, céramiques, calligraphie, jade — audioguide enfants disponible", outdoor: false },
        { time: "14h00", icon: "🛍️", title: "Nanjing Road Shopping", desc: "Plus grande rue commerçante de Chine (5,5km)", outdoor: true },
        { time: "16h30", icon: "☕", title: "Maison de thé Wuyutai", desc: "Centenaire — dégustation thé vert, noir, oolong", outdoor: false },
        { time: "18h30", icon: "🌅", title: "Coucher de soleil sur le Bund", desc: "Lumière dorée sur Pudong — heure magique pour les photos", outdoor: true },
        { time: "20h00", icon: "🍽️", title: "Dîner Lost Heaven", desc: "Cuisine yunnanaise — champignons, fleurs comestibles, poulet aux herbes", outdoor: false },
      ],
    },
    {
      regionId: "shanghai", day: 19, date: "2026-10-03", dayLabel: "Samedi 3 octobre",
      title: "Disney Shanghai !", highlight: "🏰 Le plus grand Disneyland du monde",
      planB: "Fermé/complet : Shanghai Universal Studios en alternative.",
      hackSimple: "💡 Réservez TRON Lightcycle Power Run en premier — #1 mondial, files 2h+ en journée.",
      steps: [
        { time: "07h30", icon: "🚇", title: "Métro ligne 11 — Disneyland Station", desc: "45 min depuis le centre. Arrivée à l'ouverture (9h).", outdoor: false },
        { time: "09h00", icon: "🏰", title: "Shanghai Disneyland — Opening !", desc: "Château Enchanted Storybook 2× plus grand que Cinderella Castle", outdoor: true },
        { time: "09h15", icon: "🎡", title: "TRON Lightcycle Power Run", desc: "Attraction la plus avancée technologiquement au monde — montez EN PREMIER", outdoor: true },
        { time: "11h00", icon: "🌊", title: "Pirates of the Caribbean", desc: "Version unique au monde — technologie et scénographie incomparables", outdoor: false },
        { time: "15h30", icon: "🎪", title: "Parade de l'après-midi", desc: "Costumes exclusifs à Shanghai — 16h30 sur Main Street", outdoor: true },
        { time: "19h00", icon: "🎆", title: "Ignite the Dream — Spectacle nocturne", desc: "Feux d'artifice + projection sur le château — final magique", outdoor: true },
      ],
    },
    {
      regionId: "shanghai", day: 20, date: "2026-10-04", dayLabel: "Dimanche 4 octobre",
      title: "Concession Française & Souvenirs", highlight: "🇫🇷 Un parfum de Paris au cœur de Shanghai",
      planB: "Pluie : Jing'an Kerry Centre (shopping premium couvert).",
      hackSimple: "💡 Dernier jour = chasse aux souvenirs ! Tianzifang pour l'artisanat, Nanjing Road pour les marques.",
      steps: [
        { time: "09h00", icon: "☕", title: "Brunch Concession Française", desc: "Cafés franco-chinois, brioches, congee, croissants au sésame", outdoor: false },
        { time: "10h30", icon: "🌳", title: "Wukang Road & Avenue Hengshan", desc: "Rues les plus photogéniques de Shanghai — platanes centenaires, Art Déco", outdoor: true },
        { time: "12h30", icon: "🍽️", title: "Dernier déjeuner — Xiaolongbao", desc: "Tim Ho Wan ou Crystal Jade — les raviolis soupe définitifs", outdoor: false },
        { time: "14h30", icon: "🎨", title: "Tianzifang — Derniers souvenirs", desc: "Aquarelles, soie, thés, éventails peints, figurines", outdoor: true },
        { time: "19h30", icon: "🍷", title: "Dîner d'adieu sur le Bund", desc: "Vue sur la skyline illuminée — lever de verres sur 21 jours inoubliables", outdoor: false },
        { time: "22h00", icon: "🌉", title: "Dernière balade sur le Bund", desc: "Gravez cette image — au revoir Shanghai", outdoor: true },
      ],
    },
    {
      regionId: "shanghai", day: 21, date: "2026-10-05", dayLabel: "Lundi 5 octobre",
      title: "Retour en France", highlight: "✈️ Vol AF129 Shanghai → Paris CDG",
      planB: "Vol en retard : salon Air France à Pudong + shopping duty-free.",
      hackSimple: "💡 Prenez le Maglev (430 km/h) depuis Longyang Road jusqu'à Pudong — 8 minutes, dernière expérience tech !",
      steps: [
        { time: "08h00", icon: "🍳", title: "Petit-déjeuner & check-out", desc: "Buffet, bagages, check-out", outdoor: false },
        { time: "09h30", icon: "🚄", title: "Maglev vers Pudong", desc: "430 km/h — 8 minutes depuis Longyang Road. Dernière expérience unique !", outdoor: false },
        { time: "11h00", icon: "🛫", title: "Enregistrement Air France", desc: "Comptoir AF, bagages, sécurité, salon.", outdoor: false },
        { time: "13h30", icon: "✈️", title: "Vol AF129 Shanghai → Paris CDG", desc: "Décollage 14h20 · 11h30 · Arrivée 19h50 heure Paris", outdoor: false },
        { time: "19h50", icon: "🏠", title: "Arrivée Paris CDG", desc: "Bienvenue à la maison, Famille Martin ! Souvenirs plein les valises, plein la tête.", outdoor: false },
      ],
    },
  ],

  transports: [
    {
      id: "t1", type: "Avion", icon: "✈️",
      from: "Paris CDG", to: "Pékin Capital (PEK)",
      company: "Air France", ref: "AF128", duration: "10h05", class: "Économique Flex",
      cost: 2800, costNote: "famille 4 pers.", booked: true,
      departTime: "08h10", arrivalTime: "22h15 (+1)", date: "15 sept. 2026",
      notes: "Vol direct A/R — retour inclus (AF129).",
    },
    {
      id: "t2", type: "TGV", icon: "🚄",
      from: "Pékin Ouest", to: "Xi'an Nord",
      company: "China Railway · Fuxing", ref: "G87", duration: "4h29", class: "1ère classe",
      cost: 120, costNote: "famille 4 pers.", booked: false,
      departTime: "18h02", arrivalTime: "22h31", date: "19 sept. 2026",
      notes: "Réserver sur Trip.com ou 12306.cn — 30 jours avant.",
    },
    {
      id: "t3", type: "TGV", icon: "🚄",
      from: "Xi'an Nord", to: "Chengdu Est",
      company: "China Railway · Fuxing", ref: "G308", duration: "3h25", class: "1ère classe",
      cost: 95, costNote: "famille 4 pers.", booked: false,
      departTime: "16h12", arrivalTime: "19h37", date: "23 sept. 2026",
      notes: "Réserver en même temps que Pékin → Xi'an.",
    },
    {
      id: "t4", type: "Avion", icon: "✈️",
      from: "Chengdu Tianfu", to: "Shanghai Pudong",
      company: "Air China", ref: "CA4505", duration: "2h35", class: "Économique",
      cost: 195, costNote: "famille 4 pers.", booked: false,
      departTime: "18h35", arrivalTime: "21h10", date: "27 sept. 2026",
      notes: "Réserver sur Air China ou Ctrip.",
    },
    {
      id: "t5", type: "Maglev", icon: "⚡",
      from: "Shanghai Longyang", to: "Aéroport Pudong",
      company: "Shanghai Maglev", ref: "—", duration: "8 min", class: "Standard",
      cost: 20, costNote: "famille 4 pers.", booked: false,
      departTime: "À la demande", arrivalTime: "8 min après", date: "5 oct. 2026",
      notes: "430 km/h — ne ratez pas cette expérience de science-fiction !",
    },
    {
      id: "t6", type: "Avion", icon: "✈️",
      from: "Shanghai Pudong", to: "Paris CDG",
      company: "Air France", ref: "AF129", duration: "11h30", class: "Économique Flex",
      cost: 0, costNote: "inclus dans billet A/R", booked: true,
      departTime: "14h20", arrivalTime: "19h50", date: "5 oct. 2026",
      notes: "Check-in en ligne 30h avant le départ.",
    },
  ],

  checklist: [
    {
      category: "Documents essentiels", icon: "📄",
      items: [
        { id: "c1", label: "Passeports valides 6 mois après le retour (× 4)", critical: true },
        { id: "c2", label: "Assurance voyage famille — min. 500 000€ médical", critical: true },
        { id: "c3", label: "Billets avion imprimés + version mobile", critical: true },
        { id: "c4", label: "Vouchers hôtels confirmés (4 étapes)", critical: true },
        { id: "c5", label: "Carnet de vaccination à jour (recommandé)", critical: false },
      ],
    },
    {
      category: "Technologie & Connectivité", icon: "📱",
      items: [
        { id: "c6", label: "eSIM Chine activée (Airalo — 10GB/21j · ~25€/pers)", critical: true },
        { id: "c7", label: "VPN installé sur TOUS les appareils (ExpressVPN)", critical: true },
        { id: "c8", label: "WeChat installé + compte ouvert (paiements locaux)", critical: true },
        { id: "c9", label: "DiDi installé (Uber chinois)", critical: false },
        { id: "c10", label: "Adaptateur prise type A/I (Chine)", critical: true },
        { id: "c11", label: "Power bank 20 000 mAh × 2", critical: false },
        { id: "c12", label: "App traduction offline (DeepL ou Google Translate)", critical: true },
      ],
    },
    {
      category: "Santé & Pharmacie", icon: "💊",
      items: [
        { id: "c13", label: "Anti-diarrhée — cuisine épicée !", critical: true },
        { id: "c14", label: "Trousse pharmacie complète", critical: true },
        { id: "c15", label: "Protection solaire SPF 50+", critical: false },
        { id: "c16", label: "Répulsif moustiques (Chengdu zone humide)", critical: false },
        { id: "c17", label: "Médicaments ordonnance + attestation traduite", critical: true },
      ],
    },
    {
      category: "Finances", icon: "💳",
      items: [
        { id: "c18", label: "Carte Revolut chargée", critical: true },
        { id: "c19", label: "Yuans en espèces (500¥/pers. pour marchés et street food)", critical: true },
        { id: "c20", label: "2ème carte bancaire (backup)", critical: true },
      ],
    },
  ],

  lexique: [
    { id: "l1", fr: "Bonjour", pinyin: "Nǐ hǎo", chinese: "你好", context: "Salutation universelle" },
    { id: "l2", fr: "Merci beaucoup", pinyin: "Xièxiè nǐ", chinese: "谢谢你", context: "Après tout service ou achat" },
    { id: "l3", fr: "Combien ça coûte ?", pinyin: "Duōshǎo qián?", chinese: "多少钱？", context: "Marchés, boutiques" },
    { id: "l4", fr: "Pas épicé !", pinyin: "Bù là!", chinese: "不辣！", context: "Pour les enfants au restaurant" },
    { id: "l5", fr: "Où sont les toilettes ?", pinyin: "Xǐshǒujiān zài nǎlǐ?", chinese: "洗手间在哪里？", context: "Urgent partout" },
    { id: "l6", fr: "C'est délicieux !", pinyin: "Hǎo chī!", chinese: "好吃！", context: "Compliment universel" },
    { id: "l7", fr: "Pas de coriandre SVP", pinyin: "Bù yào xiāngcài", chinese: "不要香菜", context: "Très courant en Chine" },
    { id: "l8", fr: "Je suis allergique à…", pinyin: "Wǒ duì… guòmǐn", chinese: "我对…过敏", context: "Allergie alimentaire" },
    { id: "l9", fr: "Appelez une ambulance !", pinyin: "Jiào jiùhùchē!", chinese: "叫救护车！", context: "Urgence médicale" },
    { id: "l10", fr: "Appelez la police !", pinyin: "Jiào jǐngchá!", chinese: "叫警察！", context: "Urgence sécurité" },
    { id: "l11", fr: "Je ne comprends pas", pinyin: "Wǒ bù dǒng", chinese: "我不懂", context: "Communication difficile" },
    { id: "l12", fr: "Emmenez-moi à l'hôtel", pinyin: "Qǐng sòng wǒ dào zhège jiǔdiàn", chinese: "请送我到这个酒店", context: "Montrez la carte à l'écran" },
  ],

  runbook: [
    { id: "r1", label: "Vols Air France A/R (AF128 / AF129)", status: "done", alertDate: null, ref: "AF-LV2026-CHN047", notes: "4 billets éco flex — payés en 3×." },
    { id: "r2", label: "Hôtel Pékin — Grand Millennium", status: "done", alertDate: null, ref: "GMILBJ-0926", notes: "4 nuits, 2 chambres communicantes, petit-déj inclus." },
    { id: "r3", label: "Hôtel Xi'an — Sofitel Legend", status: "done", alertDate: null, ref: "SFT-XA-0920", notes: "3 nuits, suite familiale." },
    { id: "r4", label: "Hôtel Chengdu — Niccolo", status: "done", alertDate: null, ref: "NCC-CD-0924", notes: "3 nuits, vue sur le centre." },
    { id: "r5", label: "Hôtel Shanghai — The Bund Marriott", status: "done", alertDate: null, ref: "MRRT-SH-0928", notes: "7 nuits, chambre familiale vue Bund." },
    { id: "r6", label: "Cité Interdite — Billets (quota 40 000/j !)", status: "pending", alertDate: "2026-07-16", notes: "Réserver sur gugongmuseum.com exactement 60j avant." },
    { id: "r7", label: "Armée de Terre Cuite — Billets", status: "pending", alertDate: "2026-08-06", notes: "Réserver sur bmy.com.cn 45j avant." },
    { id: "r8", label: "Trains rapides × 3 trajets (1ère classe)", status: "pending", alertDate: "2026-08-15", notes: "Trip.com ou 12306.cn — s'ouvrent 30j avant la date." },
    { id: "r9", label: "Vol interne Chengdu → Shanghai (CA4505)", status: "pending", alertDate: "2026-08-01", notes: "Air China ou Ctrip — réserver maintenant." },
    { id: "r10", label: "Disney Shanghai — Billets + Fast Pass TRON", status: "pending", alertDate: "2026-09-03", notes: "Appli Shanghai Disney Resort — ouvrir dès minuit." },
    { id: "r11", label: "eSIM Chine × 4 (Airalo)", status: "pending", alertDate: "2026-09-12", notes: "À activer le jour du départ." },
    { id: "r12", label: "VPN abonnement actif avant départ", status: "pending", alertDate: "2026-09-10", notes: "ExpressVPN ou NordVPN — tester sur mobile + ordi." },
    { id: "r13", label: "Check-in Air France en ligne", status: "pending", alertDate: "2026-09-13", notes: "30h avant décollage — bloquer sièges famille côte à côte." },
  ],

  urgences: {
    local: [
      { label: "Police", number: "110", desc: "Urgences police nationale" },
      { label: "Ambulance (SAMU)", number: "120", desc: "Urgences médicales" },
      { label: "Pompiers", number: "119", desc: "Incendie et secours" },
      { label: "Urgences touristes", number: "12301", desc: "Service national touriste 24h/24" },
    ],
    embassy: [
      { label: "Ambassade de France — Pékin", number: "+86 10 8531 2000", desc: "3 Sanlitun Dongsamjie, Pékin", hours: "24h/24" },
      { label: "Consulat de France — Shanghai", number: "+86 21 6103 2200", desc: "1431 Huaihai Zhong Lu, Shanghai", hours: "Lun–Ven 9h–12h" },
      { label: "Centre de Crise MAE Paris", number: "+33 1 30 90 37 30", desc: "Ministère des Affaires Étrangères", hours: "24h/24" },
    ],
    insurance: {
      company: "Allianz Travel",
      policy: "AZ-2026-CHN-MART",
      phone: "+33 1 40 25 25 25",
      email: "assistance@allianz-travel.fr",
      cover: "500 000€ médical · Rapatriement · Annulation",
    },
    hotels: [
      { city: "Pékin", name: "Grand Millennium Beijing", address: "7 Jianguomennei Dajie, Dongcheng", phone: "+86 10 8519 6868", chinese: "北京千禧大酒店" },
      { city: "Xi'an", name: "Sofitel Legend Peoples Grand", address: "319 Dongxin Jie, Beilin District", phone: "+86 29 8792 8888", chinese: "西安索菲特传奇大酒店" },
      { city: "Chengdu", name: "Niccolo Chengdu", address: "28 Taikoo Li North, Jinjiang District", phone: "+86 28 6262 9999", chinese: "成都尼科罗酒店" },
      { city: "Shanghai", name: "The Bund Hotel by Marriott", address: "199 Huangpu Lu, Hongkou District", phone: "+86 21 2312 9600", chinese: "上海外滩万豪酒店" },
    ],
    phrases: [
      { fr: "Appelez une ambulance !", pinyin: "Jiào jiùhùchē!", chinese: "叫救护车！" },
      { fr: "Appelez la police !", pinyin: "Jiào jǐngchá!", chinese: "叫警察！" },
      { fr: "Je suis blessé(e)", pinyin: "Wǒ shòushāng le", chinese: "我受伤了" },
      { fr: "Emmenez-moi à l'hôpital", pinyin: "Sòng wǒ qù yīyuàn", chinese: "送我去医院" },
    ],
  },
};
